### ISSUE TITLE
Cannot display server errors

### ISSUE THREAD

**Issue by LoveIsGrief** [balderdashy/sails-generate-views-jade#7]
Hi,

[res.serverError](http://sailsjs.org/#/documentation/reference/res/res.serverError.html) for sails 0.10 changed and errors are now passed to the view with this notice:

> If Sails serves a view, the data argument will be accessible as a view local: **data**.

Which means that 500.jade should be using `data.errors` instead of simply using `errors`.  
Could the view be updated please? Maybe there are other views with this behavior as well.

Cheers.

**Comment by CWyrtzen** [comment]
@LoveIsGrief Was this handled in a new release?

**Comment by LoveIsGrief** [comment]
There haven't been any updates since I created this bug-report and I don't know of a new release. I don't think there have been any improvements.  
Maybe when I get around to it, I'll do it myself. Otherwise maybe you could ;) ... or the original devs.

**Comment by CWyrtzen** [comment]
Released v0.11 stable on Feb 10 2015  https://github.com/balderdashy/sails/blob/master/0.11-migration-guide.md
